{
 "title": "openstack监控",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "总内存",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "gbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(openstack_total_used_ram_MB+openstack_total_free_ram_MB)/1000"
    }
   ]
  },
  {
   "title": "硬盘总存储",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(openstack_total_free_disk_GB+openstack_total_used_disk_GB)"
    }
   ]
  },
  {
   "title": "vcpu总数（个）",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "openstack_total_free_vcpus" }
   ]
  },
  {
   "title": "openstack运行情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "正常运行的占比(%)" }
   ],
   "targets": [
    {
     "expr": "openstack_services_nova_conductor_up_percent",
     "legendFormat": "计算调度"
    },
    {
     "expr": "openstack_services_neutron_dhcp_agent_up_percent",
     "legendFormat": "dhcp服务"
    },
    {
     "expr": "openstack_services_neutron_linuxbridge_agent_up_percent",
     "legendFormat": "网络桥接服务"
    },
    {
     "expr": "openstack_services_nova_compute_up_percent",
     "legendFormat": "计算服务"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "openstack_total_used_ram_MB/1000",
     "legendFormat": "内存占用情况"
    }
   ]
  },
  {
   "title": "硬盘存储使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    { "expr": "openstack_used_disk_GB" },
    { "expr": "sum(openstack_used_disk_GB)", "legendFormat": "总存储" }
   ]
  },
  {
   "title": "vcpu使用情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "openstack_used_vcpus" }
   ]
  },
  {
   "title": "实例个数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openstack_total_running_instances"
    }
   ]
  },
  {
   "title": "硬盘剩余存储",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "format": "gbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "openstack_total_free_disk_GB" }
   ]
  }
 ]
}