apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
    - port: 3000
      nodePort: 30006
  selector:
        app: test
        tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test
        tier: frontend
    spec:
      containers:
      - image: 192.168.33.61/test/grafana-grafana:6.0.1
        name: test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
           - mountPath: /etc/grafana/provisioning/datasources
             name: grafana-datasources-config
           - mountPath: /etc/grafana/provisioning/dashboards
             name: grafana-dashboard-config
           - mountPath: /var/lib/grafana
             name: grafana-storage
             readOnly: false
           - mountPath: /tmp/grafana
             name: grafana-dashboard-json-config
      volumes:
         - name: grafana-datasources-config
           configMap:
               name: grafana-datasources
         - name: grafana-dashboard-config
           configMap:
               name: grafana-dashboard
         - name: grafana-dashboard-json-config
           configMap:
               name: grafana-dashboard-json
         - emptyDir: {}
           name: grafana-storage
