apiVersion: v1
kind: Service
metadata:
  name: metrics
  labels:
    app: metrics
spec:
  ports:
    - port: 9108
      nodePort: 30003
  selector:
    app: metrics
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics
  labels:
    app: metrics
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metrics
        tier: frontend
    spec:
      containers:
      - image: 192.168.33.61/test/openstack-exporter:v1
        name: metrics
        imagePullPolicy: IfNotPresent
        envFrom:
            - configMapRef:
                 name: openstack-env
        ports:
        - containerPort: 9108
          name: metrics
       
       
