apiVersion: v1
kind: Service
metadata:
  name: test-data
  labels:
    app: test
spec:
  ports:
    - port: 9090
      nodePort: 30004
  selector:
    app: test
    tier: data
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-data
  labels:
    app: test
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test
        tier: data
    spec:
      containers:
      - image: prom/prometheus:latest
        name: data
        imagePullPolicy: IfNotPresent
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
        - containerPort: 9090
          name: data
        volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-env
        
       
       
